apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-auth
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: management
  selector:
    app: {{ .Release.Name }}-auth
  sessionAffinity: None
  type: ClusterIP