replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-keycloak
  pullPolicy: IfNotPresent
  sha256: b44d77ef71364fc99a3bcf5d8f087c2972ce6b8dc4f8bc33d6b5badd9fdad976

resources:
  limits:
    cpu: 250m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

startupProbe:
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30

readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
