replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-api
  pullPolicy: Always
  sha256: b7153c0a3c6a759931e1693b600d891ee8df9494fa802a5013e716c4a9c2d3ba

metadata:
  annotations:
    reloader.stakater.com/auto: "true"

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 1
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi