replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-api
  pullPolicy: Always
  sha256: 0b136bcb51e4dbedeccc4f99341235da629a3205bd94b882c55d9f6c1fbdc14c

metadata:
  annotations:
    reloader.stakater.com/auto: "true"

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 1
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi