replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-management
  pullPolicy: Always
  sha256: 2dbf8c0d0326cc0a8e26952b8a11c65c6e0e7b13cd67fdf7e6cdb02771df0e99

metadata:
  annotations:
    reloader.stakater.com/auto: "true"

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 1
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi