replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-management
  pullPolicy: Always
  sha256: c76153f1124cc99f7f94ad0df8b5942bfecea0f01d64e9a8f9aad89f3661eab4

metadata:
  annotations:
    reloader.stakater.com/auto: "true"

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 1
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi