replicaCount: 1

image:
  repository: ghcr.io/metatavu/noheva-management
  pullPolicy: Always
  sha256: e3ece5b0aba4b3a79eb6ab698c15e41d7e0137273f0ffedf6767dcf50e433b6d

metadata:
  annotations:
    reloader.stakater.com/auto: "true"

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 1
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi