apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-api
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-api
  sessionAffinity: None
  type: ClusterIP