apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-api-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: runtime-noheva-api
      metadataPolicy: None
  refreshInterval: 60s
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Release.Name }}-api-secrets